version: '3.8'

services:
  arfly-server:
    image: ${DOCKER_USERNAME}/arfly-server:latest
    container_name: arfly-spring
    restart: always
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - FIREBASE_KEY_PATH=${FIREBASE_KEY_PATH}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - ACCESS_EXPIRATION=${ACCESS_EXPIRATION}
    depends_on:
      - postgres
    volumes:
      - ./firebase-admin-key.json:/app/firebase-key.json

  postgres:
    image: postgres:15
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: Asia/Seoul
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: