file:
  max-image-size: 50MB

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver


  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: ${S3_BUCKET_NAME}

  servlet:
    multipart:
      max-file-size: 100MB # 비디오를 고려한 파일 최대 크기
      max-request-size: 100MB # 한번의 요청에 담을 수 있는 크기

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul


jwt:
  access-secret: ${ACCESS_SECRET}
  access-expiration: ${ACCESS_EXPIRATION}
  refresh-secret: ${REFRESH_SECRET}
  refresh-expiration: ${REFRESH_EXPIRATION}
  password-reset-secret: ${PASSWORD_RESET_SECRET}
  password-reset-expiration: ${PASSWORD_RESET_EXPIRATION}


oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_SECRET}
    grant-type: ${GOOGLE_TYPE}

  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_SECRET}

  naver:
    client_id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_SECRET}

app:
  user:
    id: ${TEST_USER_ID}
    password: ${TEST_USER_PASSWORD}

